# name: github pages

# on:
#   push:
#     branches:
#       - main # Set a branch to deploy
#   pull_request:

# jobs:
#   deploy:
#     runs-on: ubuntu-20.04
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           submodules: true # Fetch Hugo themes (true OR recursive)
#           fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

#       - name: Setup Hugo
#         uses: peaceiris/actions-hugo@v2
#         with:
#           hugo-version: "latest"
#           extended: true

#       - name: Build
#         run: hugo --minify

#       - name: Deploy
#         uses: peaceiris/actions-gh-pages@v3
#         if: github.ref == 'refs/heads/main'
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: ./public

name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Hugo Deploy GitHub Pages
        uses: benmatselby/hugo-deploy-gh-pages@master
        env:
          HUGO_VERSION: 0.84.1
          TARGET_REPO: comma-lab/comma-lab.github.io
          TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          # CNAME: www.jameswright.xyz
